[package]
name = "excel_test"
version = "0.1.0"
authors = ["Bevan Hunt <bevan@bevanhunt.com>"]
edition = "2018"

[dependencies]
calamine = "0.15.4"
actix-multipart = "0.1.1"
actix-web = "1.0.0-rc"
futures = "0.1.27"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
concat-string = "1.0.1"
